// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240208192758_additional_cpu_and_gpu")]
    partial class additional_cpu_and_gpu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("Data.Entities.CpuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Frequency")
                        .HasColumnType("REAL");

                    b.Property<int?>("L3Cache")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TurboFrequency")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Cpus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cores = 4,
                            Frequency = 3.4f,
                            L3Cache = 6,
                            Name = "Intel i5 8600k",
                            Threads = 8,
                            TurboFrequency = 4.2f
                        },
                        new
                        {
                            Id = 2,
                            Cores = 6,
                            Frequency = 3.2f,
                            L3Cache = 12,
                            Name = "Intel i7 8700",
                            Threads = 12,
                            TurboFrequency = 4.6f
                        },
                        new
                        {
                            Id = 3,
                            Cores = 8,
                            Frequency = 3.6f,
                            L3Cache = 16,
                            Name = "Intel i9",
                            Threads = 16,
                            TurboFrequency = 5f
                        },
                        new
                        {
                            Id = 4,
                            Cores = 6,
                            Frequency = 3.4f,
                            L3Cache = 16,
                            Name = "AMD Ryzen 5 2600",
                            Threads = 12,
                            TurboFrequency = 3.9f
                        },
                        new
                        {
                            Id = 5,
                            Cores = 8,
                            Frequency = 3.2f,
                            L3Cache = 16,
                            Name = "AMD Ryzen 7 2700",
                            Threads = 16,
                            TurboFrequency = 4.1f
                        },
                        new
                        {
                            Id = 6,
                            Cores = 8,
                            Frequency = 3.7f,
                            L3Cache = 16,
                            Name = "AMD Ryzen 7 2700x",
                            Threads = 16,
                            TurboFrequency = 4.3f
                        });
                });

            modelBuilder.Entity("Data.Entities.GpuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VRam")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Gpus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Nvidia GTX 1050",
                            Manufacturer = "Nvidia",
                            VRam = 2
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nvidia GTX 1060 GB",
                            Manufacturer = "Nvidia",
                            VRam = 6
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nvidia GTX 1070",
                            Manufacturer = "Nvidia",
                            VRam = 8
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Nvidia GTX 1080",
                            Manufacturer = "Nvidia",
                            VRam = 8
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Nvidia GTX 2050",
                            Manufacturer = "Nvidia",
                            VRam = 4
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Nvidia GTX 2070",
                            Manufacturer = "Nvidia",
                            VRam = 8
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Radeon RX 570",
                            Manufacturer = "Radeon",
                            VRam = 4
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Radeon RX 580",
                            Manufacturer = "Radeon",
                            VRam = 8
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Radeon RX 590",
                            Manufacturer = "Radeon",
                            VRam = 8
                        });
                });

            modelBuilder.Entity("Data.Entities.PcEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiskType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GpuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("production_date");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CpuId");

                    b.HasIndex("GpuId");

                    b.ToTable("Pcs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3dc01775-675b-4801-8c8b-4625ce50e4f8",
                            ConcurrencyStamp = "3dc01775-675b-4801-8c8b-4625ce50e4f8",
                            Name = "user",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "bcfa132b-687f-43aa-bb68-dbda8d0241b0",
                            ConcurrencyStamp = "bcfa132b-687f-43aa-bb68-dbda8d0241b0",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00da8877-b95b-47d9-8b14-284fe5c6291a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db1b509a-b4df-41c6-b971-593e5081e47c",
                            Email = "tomek@wsei.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TOMEK@WSEI.PL",
                            NormalizedUserName = "TOMEK",
                            PasswordHash = "AQAAAAEAACcQAAAAEHt9eyLDlLPL0yGT5tyLTvPRofkejRxw05nDHzmZPloQHpaHYHd9JzLPKFq50c0p4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e2ffc74-69c5-4d96-9fbc-48cf794ebf9a",
                            TwoFactorEnabled = false,
                            UserName = "tomek"
                        },
                        new
                        {
                            Id = "cecf57bd-b989-4534-9454-ae53ada19ec2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c0de9ebd-7862-4264-9004-9b49b3a1cfd1",
                            Email = "kamil@wsei.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KAMIL@WSEI.PL",
                            NormalizedUserName = "KAMIL",
                            PasswordHash = "AQAAAAEAACcQAAAAEJmjP8XLGiQpgRVeNmFe9r+QiQpun9kwyM45Tl21xezSugIvspzKIVia+bVJsZlRcw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "42c0ada7-cb8b-457f-8ccd-873bb199da4f",
                            TwoFactorEnabled = false,
                            UserName = "kamil"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "00da8877-b95b-47d9-8b14-284fe5c6291a",
                            RoleId = "bcfa132b-687f-43aa-bb68-dbda8d0241b0"
                        },
                        new
                        {
                            UserId = "cecf57bd-b989-4534-9454-ae53ada19ec2",
                            RoleId = "3dc01775-675b-4801-8c8b-4625ce50e4f8"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.PcEntity", b =>
                {
                    b.HasOne("Data.Entities.CpuEntity", "Cpu")
                        .WithMany("Pcs")
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.GpuEntity", "Gpu")
                        .WithMany("Pcs")
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");

                    b.Navigation("Gpu");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.CpuEntity", b =>
                {
                    b.Navigation("Pcs");
                });

            modelBuilder.Entity("Data.Entities.GpuEntity", b =>
                {
                    b.Navigation("Pcs");
                });
#pragma warning restore 612, 618
        }
    }
}
